name: 'Install node and dependencies'
description: 'Install node and dependencies'
runs:
  using: "composite"
  steps:
    - name: Setup node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      shell: bash
      run: npm ci
