name: 'Semver'
description: 'Provides the next semantic version'

branding:
  icon: 'bookmark'
  color: 'purple'

inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  dev-version-suffix:
    description: 'E.g. 1.42.0-<dev-version-suffix>'
    default: DEV
    required: true

outputs:
  semver:
    description: 'The next semantic version.'

runs:
  using: node20
  main: dist/index.js

author: "Michael Hienle"